type: sns
name: sns_standard
chain_depth: [1, 3]
params:
  jpeg_q: [50, 90]
  webp_q: [50, 90]
  resize_long: [0, 0]
  aspect_ratio: [0.6, 1.8]
  noise_sigma: [0.0, 3.0]
  gamma: [0.8, 1.2]
  contrast: [0.8, 1.2]
  saturation: [0.8, 1.2]
  brightness: [0.85, 1.15]
  repeats: [1, 3]
  watermark_alpha: [0.1, 0.25]
