type: sns
name: sns_robust
chain_depth: [2, 4]
params:
  jpeg_q: [35, 85]
  webp_q: [35, 85]
  resize_long: [448, 2048]
  aspect_ratio: [0.5, 2.2]
  noise_sigma: [0.0, 4.0]
  gamma: [0.75, 1.25]
  contrast: [0.75, 1.25]
  saturation: [0.75, 1.25]
  brightness: [0.8, 1.2]
  repeats: [2, 4]
  watermark_alpha: [0.1, 0.35]
