defaults:
  - experiment: default
  - logging: default
  - augment: sns_standard
  - model: vit_residual_fusion
  - dataset: sns_standard_dataset
  - trainer: default
  - optimizer: adamw
  - scheduler: cosine
  - _self_

run:
  seed: 1337
  output_dir: ${oc.env:TVB_EXPERIMENT_ROOT,${hydra:runtime.cwd}/experiments}/${model.name}/${now:%Y%m%d_%H%M%S}

resume: null

experiment_name: ${model.name}
