defaults:
  - experiment: default
  - hydra: default
  - logging: default
  - augment: sns_standard
  - model: vit_residual_fusion
  - dataset: sns_standard_dataset
  - trainer: default
  - optimizer: adamw
  - scheduler: cosine
  - _self_
