defaults:
  - dataset: sns_standard_dataset
  - augment: sns_standard
  - optimizer: adamw
  - scheduler: cosine
  - trainer: default
  - logging: default
  - _self_

seed: 1337

model:
  name: vit_residual_fusion
  params:
    vit_name: vit_base_patch16_224
    num_classes: 2
    pretrained: true
    residual_embed_dim: 160

optimizer:
  name: adamw
  lr: 5.0e-5
  weight_decay: 0.05

scheduler:
  name: cosine
  warmup_epochs: 3
  min_lr: 1.0e-6

trainer:
  epochs: 24
  grad_accum_steps: 2
  mixed_precision: fp16
  label_smoothing: 0.05
  log_interval: 50
  criterion: ce
  early_stopping:
    enabled: true
    patience: 5
    monitor: val_loss
    mode: min

run:
  seed: 1337
  output_dir: ${oc.env:TVB_EXPERIMENT_ROOT,${hydra:runtime.cwd}/experiments}/${model.name}/${now:%Y%m%d_%H%M%S}
  name: vit_residual_multiscale

dataset:
  data_root: /home/smin/datasets/genimage
  source: imagenet_ai_0508_adm
  loader:
    batch_size: 256
    num_workers: 18

augment:
  sns:
    jpeg_q: [35, 90]
    webp_q: [35, 90]
    resize_long: [512, 2048]
    noise_sigma: [0.0, 4.0]
    gamma: [0.8, 1.2]
    repeats: [1, 3]
    watermark_alpha: [0.1, 0.3]

inference:
  multiscale: [224, 336, 512]
  cell_sizes: [256, 384, 640]
  n_patches: 0
  patch_overlap: 0.25
  patch_jitter: 0.1
  max_patches: 24
  aggregate: mean
  uncertain_band: [0.45, 0.55]

logging:
  level: INFO
