experiment:
  name: vit_b16_alpha
  output_root: ../../experiments
seed: 42

data:
  train_dir: /path/to/train
  val_dir: /path/to/val
  batch_size: 32
  num_workers: 4
  img_size: 224

model:
  name: vit_b16
  params:
    num_classes: 2
    pretrained: true

optimizer:
  name: adamw
  lr: 3.0e-4
  weight_decay: 0.05

trainer:
  epochs: 20
  mixed_precision: bf16  # or fp16 / no
  grad_accum_steps: 1
  log_interval: 50
  save_interval: 1

