seed: 1337

model:
  name: vit_residual
  vit_name: vit_base_patch16_224_in21k
  num_classes: 2
  residual:
    embed_dim: 128

train:
  img_size: 224
  batch_size: 256
  epochs: 40
  optimizer:
    name: adamw
    lr: 1.0e-4
    weight_decay: 0.05
  scheduler:
    name: cosine
    warmup_epochs: 3
  grad_accum_steps: 1
  mixed_precision: fp16
  log_interval: 50
  criterion: ce

data:
  datasets:
    - name: coco
      path: /data/coco
      weight: 1
    - name: openimages
      path: /data/openimages
      weight: 1
    - name: ai_images
      path: /data/ai_images  # TODO: AI 데이터셋 추가 (삭제 금지)
      weight: 1
  output_dir: /data/mixed
  sampling:
    ratio: 0.5
    seed: 1337
    policy: once
  train_dir: /data/mixed/train
  val_dir: /data/mixed/val
  num_workers: 16

augment:
  sns:
    jpeg_q: [35, 90]
    webp_q: [35, 90]
    resize_long: [512, 2048]
    noise_sigma: [0.0, 8.0]
    gamma: [0.8, 1.2]
    repeats: [1, 3]

inference:
  multiscale: [224, 336]
  n_patches: 12
  aggregate: mean
  uncertain_band: [0.45, 0.55]

logging:
  level: INFO
