experiment:
  name: vit_multipatch_alpha
  output_root: ../../experiments
seed: 42

data:
  train_dir: /path/to/train
  val_dir: /path/to/val
  batch_size: 24
  num_workers: 4
  img_size: 256

model:
  name: vit_multipatch
  params:
    num_classes: 2
    pretrained: true
    crop_scales: [1.0, 0.8]
    corner_crops: true

optimizer:
  name: adamw
  lr: 3.0e-4
  weight_decay: 0.05

trainer:
  epochs: 20
  mixed_precision: bf16
  grad_accum_steps: 1
  log_interval: 50
  save_interval: 1

