seed: 1337

model:
  name: residual
  params:
    in_channels: 3
    embed_dim: 128

train:
  img_size: 224
  batch_size: 768  # per-process batch (A40 2장 → global ~1536)
  epochs: 40
  optimizer:
    name: adamw
    lr: 1.0e-4
    weight_decay: 0.05
  scheduler:
    name: cosine
    warmup_epochs: 3
  grad_accum_steps: 2  # 메모리 여유 없을 때 누적 그라드로 안정화
  mixed_precision: fp16
  log_interval: 50
  criterion: ce

data:
  datasets: []  # 샘플링 비활성화(직접 경로 사용)
  # 실제 데이터 경로(폴더: real, z_ai)
  train_dir: /home/smin/datasets/genimage/ADM/imagenet_ai_0508_adm/train
  val_dir:   /home/smin/datasets/genimage/ADM/imagenet_ai_0508_adm/val
  num_workers: 12

augment:
  sns:
    jpeg_q: [35, 90]
    webp_q: [35, 90]
    resize_long: [512, 2048]
    noise_sigma: [0.0, 8.0]
    gamma: [0.8, 1.2]
    repeats: [1, 3]

inference:
  multiscale: [224, 336]
  n_patches: 12
  aggregate: mean
  uncertain_band: [0.45, 0.55]

logging:
  level: INFO
