defaults:
  - base
  - augment: sns_robust
  - _self_

name: sns_robust_dataset
loader:
  batch_size: 96
  num_workers: 16
train:
  transforms:
    - type: RandomResizedCrop
      size: ${dataset.image_size}
      scale: [0.6, 1.0]
    - type: ColorJitter
      brightness: 0.25
      contrast: 0.25
      saturation: 0.25
      hue: 0.05
    - type: RandomHorizontalFlip
